"""add detection_reason

Revision ID: 2b5591c27d99
Revises: 3a0fd0e05786
Create Date: 2026-07-10 10:22:45.894381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5591c27d99'
down_revision = '3a0fd0e05786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kids_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detection_reason', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kids_images', schema=None) as batch_op:
        batch_op.drop_column('detection_reason')

    # ### end Alembic commands ###
