"""add genre and comment

Revision ID: 3a0fd0e05786
Revises: 2de8bdffdcc3
Create Date: 2026-07-03 10:47:25.167232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0fd0e05786'
down_revision = '2de8bdffdcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kids_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kids_images', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
